project:
  type: website
  output-dir: docs

  

  
website:
  title: "Mr Weatherall Science"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - physics.qmd
      - digitaltech.qmd
      - projects.qmd 
      - blog.qmd
  page-footer: 
    left: "© 2025 Alex Weatherall - built with Quarto"
    background: light
    border: true
  
  open-graph: true

  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Under Construction** - this is a new website - still working on it."
    type: warning
    position: below-navbar
  sidebar: 
    contents: auto
    style: "docked"
    search: true
  


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location:  right
    bread-crumbs: false
    html-math-method: katex
    link-external-icon: true
    link-external-newwindow: true
    page-layout: full
    anchor-sections: true
    smooth-scroll: true
    title-block-banner: true
  #typst: 
  #  papersize: a4
  #  margin:
  #    x: 1cm
  #    y: 1cm
  #  columns: 1

